### ISSUE TITLE
reporte de entrevista

### ISSUE THREAD

**Issue by Arnold-Js** [SistemasTecTlaxiaco/entrevista-disttecpersis#1]
[Informe de la entrevista.docx](https://github.com/SistemasTecTlaxiaco/entrevista-disttecpersis/files/7147232/Informe.de.la.entrevista.docx)

**Comment by Abraham890** [comment]
Calificación: 20/20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
